version: "3.4"
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /mnt/NAS:/mnt

  plex:
    container_name: plex
    network_mode: bridge
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - PLEX_CLAIM=
    volumes:
      - ~/config/plex:/config
      - /mnt/NAS:/media

  redbot:
    container_name: redbot
    image: ghcr.io/phasecorex/red-discordbot:full
    restart: unless-stopped
    volumes:
      - ~/config/redbot:/data
    environment:
      - TOKEN=
      - PREFIX=-
      - PUID=1000
      - TZ=Europe/Rome

  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/config/heimdall:/config
